[tool.poetry]
name = "lab1_Suhangulyyev_M"
version = "0.1.2"
description = "CRUD API for a news portal (Fastapi)."
authors = ["Muhammet Suhangulyyev <muhammet.jkl2.suhanguylev@gmail.com>"]
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.0"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.40"}
asyncpg = "^0.30.0"
alembic = "^1.16.0"
pydantic = {extras = ["email"], version = "^2.10.0"}
pydantic-settings = "^2.10.0"
psycopg2-binary = "^2.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-cov = "^6.2.0"
httpx = "^0.28.0"
pytest-asyncio = "^1.2.0"
