"""initial migration

Revision ID: 48641330ade0
Revises:
Create Date: 2025-10-07 13:43:07.203027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import uuid
import datetime

from app.core.security import hash_password


# revision identifiers, used by Alembic.
revision: str = "48641330ade0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "VERIFIED_AUTHOR", "USER", name="userrole"),
            nullable=False,
            server_default="USER",
        ),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "news",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cover_image_url", sa.String(length=255), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_title"), "news", ["title"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_refresh_token"),
        "refresh_tokens",
        ["refresh_token"],
        unique=True,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("news_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["news_id"], ["news.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Вставка моковых данных
    users_table = sa.table(
        "users",
        sa.column("id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("email", sa.String),
        sa.column("hashed_password", sa.String),
        sa.column("role", sa.String),
        sa.column("registered_at", sa.DateTime(timezone=True)),
    )
    news_table = sa.table(
        "news",
        sa.column("id", sa.UUID),
        sa.column("title", sa.String),
        sa.column("content", sa.JSON),
        sa.column("author_id", sa.UUID),
        sa.column("published_at", sa.DateTime(timezone=True)),
    )

    verified_author_id = uuid.uuid4()
    regular_user_id = uuid.uuid4()
    admin_user_id = uuid.uuid4()
    news_id = uuid.uuid4()
    now = datetime.datetime.now(datetime.timezone.utc)

    op.bulk_insert(
        users_table,
        [
            {
                "id": verified_author_id,
                "name": "Verified Author",
                "email": "author@example.com",
                "hashed_password": hash_password("dummy_password"),
                "role": "VERIFIED_AUTHOR",
                "registered_at": now,
            },
            {
                "id": regular_user_id,
                "name": "Regular User",
                "email": "user@example.com",
                "hashed_password": hash_password("dummy_password"),
                "role": "USER",
                "registered_at": now,
            },
            {
                "id": admin_user_id,
                "name": "Admin User",
                "email": "admin@example.com",
                "hashed_password": hash_password("admin_password"),
                "role": "ADMIN",
                "registered_at": now,
            },
        ],
    )
    op.bulk_insert(
        news_table,
        [
            {
                "id": news_id,
                "title": "FastAPI is Awesome!",
                "content": {"text": "A detailed article about FastAPI."},
                "author_id": verified_author_id,
                "published_at": now,
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    op.drop_index(op.f("ix_refresh_tokens_refresh_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_news_title"), table_name="news")
    op.drop_table("news")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
